#defining
language: yaml
stages:
  -stage: continuos-integration
  displayname: continuosintegration  
  jobs: 
      - job: dotnetbuild
      displayname: dotnetbuildjob
  steps:
        -script: dotnetrestore
        displayname: restore
        -script: dotnetbuild
        displayname: build
        -script: dotnettest
        displayname: test
        -script: dotnetpublish
        displayname: publish
