stages:
  -stage: continuos-integration
  displayname:continuos-integration  
  jobs: 
      - job: dotnet-build
      displayname: dotnet-buildjob
      steps:
        -script: dotnet restore
        displayname: restore
        -script: dotnet build
        displayname: build
        -script: dotnet test
        displayname:  test
        -script: dotnet publish
        displayname: publish artifact
        -task:
      
      

















  -stage: continuos-Deployement